### PR TITLE
Support native matrix multiplication (among other operations)

### PR DESCRIPTION
**Pull request by LTLA**
This PR is largely intended as a discussion rather than a finished product, because the simplest way to get it to work was to make a major paradigm change to how `extract_array` works. 

Specifically, `extract_array`'s contract has now been changed so that it is only obliged to return a non-`DelayedArray` instance rather than an ordinary array. I call this the "native" representation, usually equivalent to the class of the seed if the seed is a valid array-like object in its own right (i.e., not just a `*Seed` object). Any downstream operations applied onto this `extract_array` output will subsequently use the native representation's methods, which are likely to be more efficient than a general-purpose collapsing to an ordinary matrix. This is certainly true for sparse methods, at least.

The requirement for a non-DA output is obviously necessary to avoid infinite recursion. There may be some problems in the future from packages sneakily calling DA methods within methods for non-DA classes (e.g., if their internals rely on DA intermediates) but this seems pretty contrived to me. Perhaps we could add a global option that causes ordinary coercion to accommodate such cases.

I originally wrote this to handle the sparse multiplication case, but it seems like it would provide an efficiency benefit to all utilities (e.g., column sums, row sums). Some generics without general support would need to be protected by `as.array` but this can be done on a method-by-method basis without compromising the efficiency of generics that do have such support. I have not done a check  of how many other utilities in **DelayedArray** are broken by this contract change.

I also took the liberty of transplanting the matrix multiplication code into a separate file to keep its concepts separate from the other utilities. I had originally planned to do more edits to the multiplication code but the solution turned out to be as "easy" as modifying `extract_array`.

### CODE REVIEW

**Comment by LTLA** [comment]
To give some idea of the speed improvements that I'm seeing:

```r
# OLD
library(DelayedArray)
library(Matrix)
X <- rsparsematrix(10000, 1000, 0.01)
D <- DelayedArray(X)
system.time(out <- D %*% matrix(runif(5000), ncol=5))
##    user  system elapsed 
##   0.245   0.052   0.297 
```

```r
# NEW
library(DelayedArray)
library(Matrix)
X <- rsparsematrix(10000, 1000, 0.01)
D <- DelayedArray(X)
system.time(out <- D %*% matrix(runif(5000), ncol=5))
##    user  system elapsed 
##   0.014   0.000   0.013 
```

(Putting aside the ~0.1 second overhead on the first call in both cases.)

**Comment by LTLA** [comment]
This is crazy!

```r
# OLD
system.time(rowSums(D))
##    user  system elapsed 
##   0.070   0.044   0.114 
system.time(colSums(D))
##    user  system elapsed 
##   0.360   0.088   0.447 
```

```r
# NEW
system.time(rowSums(D))
##    user  system elapsed 
##   0.005   0.000   0.005 
> system.time(colSums(D))
##    user  system elapsed 
##   0.007   0.000   0.007 
```

**Comment by LTLA** [comment]
A bit more protection but otherwise passes CHECK for me.

**Comment by lawremi** [comment]
Not sure returning a DelayedArray would lead to infinite recursion in general. Seems like an arbitrary restriction.

**Comment by LTLA** [comment]
The general principle is that `FUN,DelayedArray-method` would eventually call `extract_array` that returns a "simpler" object that we can call `FUN` on to actually get the results. Prior to this PR, this was an ordinary matrix, but as I've found out, anything that supports all of the desired `FUN` would do. However, if `extract_array` returned a DA, we'd be back where we started.

**Comment by hpages** [comment]
Interesting but you don't need to change `extract_array`'s or `read_block`'s contract for that, only `extract_sparse_array`'s and `read_sparse_block`'s contracts. I'd like to stick to the approach discussed in issue #40. With this approach walking on a sparse array is done with `read_sparse_block()` which itself relies on `extract_sparse_array()`. Let's call this "sparse block processing".

"Sparse block processing" in only enabled in a few places at the moment (in `rowsum()`, `colsum()`,  `writeHDF5Array()`, `writeTENxMatrix()`, and coercion to RleArray). Things like `rowSums(D)` don't do it yet because matrix summarization didn't work natively on dgCMatrix objects until very recently (well, we had `rowSums()` but not all the other methods that spareMatrixStats now provides). 

Right now `extract_sparse_array()` (and consequently `read_sparse_block()`) returns a SparseArraySeed  object **even in the 2D case**. However most of the time the 2D SparseArraySeed object will need to be coerced to dgCMatrix or other sparseMatrix derivative before you can do anything meaningful with it (unless we had matrix summarization also work natively on 2D SparseArraySeed objects but that's another story). You could argue that this is not optimal and you'd have a point. So you could explore having `extract_sparse_array()` and `read_sparse_block()` return a sparseMatrix derivative instead of a 2D SparseArraySeed. This should give you the same speedup as what you're observing now with your modified `extract_array()`, granted of course that you also modified `rowSums()` so it knows how to switch between "dense block processing" and "sparse block processing" (I believe that the switch would actually need to be implemented in `blockApply()`).

**Comment by hpages** [comment]
With your patch I get:
```
library(DelayedMatrixStats)
rowVars(D)
# Error in APPLY(block, ...) : Argument 'x' must be a matrix or a vector.
```
which is the reason why I didn't enable "sparse block processing" in matrix summarization methods yet. Now that sparseMatrixStats is available these methods need a serious overhaul. However I think we should start by introducing the dense/sparse switch first and then see if we also want to revisit `extract_sparse_array`'s and `read_sparse_block`'s contracts.

**Comment by LTLA** [comment]
I still don't understand the advantage of the `extract_sparse_array` approach. Seems painful to have to build up two parallel codebases for handling sparse and dense arrays when it is demonstrably possible to handle both cases with a single codebase. Either way, you're going to have to write an `if` between dense and sparse at some point, so why not let S4 dispatch on the seed take care of it?

**Comment by hpages** [comment]
Unlike `extract_array()`, `extract_sparse_array()` knows how to maintain sparsity **at all time**. For example, with DelayedArray object `D2`:
```
library(DelayedArray)
library(Matrix)
set.seed(123)
X <- rsparsematrix(10000, 1000, 0.01, rand.x=function(n) sample(200, n, replace=TRUE))
D <- DelayedArray(X)
D2 <- log(D + 1)
```
As we know `extract_array(D2, list(1:1000, 1:1000))` blows the representation to a dense one (ordinary matrix) whereas `extract_sparse_array()` returns a 2D SparseArraySeed object (whose memory footprint is 50x smaller than the dense one in this case).

Note that with your patch `extract_array(D2, list(1:1000, 1:1000))` still returns a dense representation, except that now it's a dgeMatrix instead of an ordinary matrix.

More generally I think it's important that we're able to do 2 things:
1. Recognize in advance that a DelayedArray object holds delayed operations that will propagate sparsity all the way from the seed to the top. This is what `is_sparse()` does.
2. Implement a block extraction mechanism that actually preserves sparsity all the way from the seed to the top. This is what `read_sparse_block()` does (via `extract_sparse_array()`).

Having these 2 things in place you can switch early between dense and sparse block processing. I don't think you can easily rely on dispatch for this early switch. The advantages of switching early to sparse block processing are:
- you can adjust the block size accordingly (typically make it much bigger);
- you have the **guarantee** that sparsity will be preserved at all time;
- you know **exactly** what your blocks will be like so you don't need to gamble about what operations they will support or not.

Yes unfortunately that means implementing two parallel codebases for handling sparse and dense arrays. But in practice this should not be such a pain because the switch will be implemented in a few places only e.g. in matrix multiplication, in `blockApply()`, and maybe in a few other `*apply` utilities. So situations where the end user will actually have to implement the switch should be relatively rare.

**Comment by LTLA** [comment]
As long as it gets done. But for the sake of argument:

> * you can adjust the block size accordingly (typically make it much bigger);

Sounds dangerous, you don't know how the non-zero elements are distributed throughout the matrix. If you were to make the block size much bigger, you could get exactly what you asked for if all the non-zero elements were concentrated in one block.

> * you have the **guarantee** that sparsity will be preserved at all time;

To continue on the `log(D + 1)` example, the sparsity-preserving operation would be `log1p`. I'm not concerned about loss of sparsity with `log(D + 1)` given that **Matrix** doesn't attempt to preserve sparsity either. This sentiment applies generally, I know what operations are sparsity-preserving or not and I don't expect **DelayedArray** to be too smart about it.

> * you know **exactly** what your blocks will be like so you don't need to gamble about what operations they will support or not.

You're going to have to write all the extra operations for sparse matrices anyway, so it's no less work to guarantee support compared to the proposed approach. What's worse is that you're forcing downstream developers to adhere to "dense" or "sparse" instead of giving them a chance to support those operations in the best way possible for their seed representation.

**Comment by hpages** [comment]
> Sounds dangerous, you don't know how the non-zero elements are distributed throughout the matrix

Ok I take back the "much" in "much bigger" but in general not trying to increase the block size when you know that the memory footprint of your blocks is going to be reduced by 50x in average would be silly.

> I know what operations are sparsity-preserving or not and I don't expect DelayedArray to be too smart about it.

But you don't decide what operations others put on their DelayedArray objects and we still want `rowSums()` to perform optimally for them right?

> What's worse is that you're forcing downstream developers to adhere to "dense" or "sparse" instead of giving them a chance to support those operations in the best way possible for their seed representation.

Developers will start to implement all kinds of crazy `extract_array()` methods. `extract_array()` is at the core of the delayed operation mechanism, not just the block processing mechanism. The delayed operation mechanism is a complex mechanism and is only maintainable because `extract_array()` has a very simple and well defined contract. I don't want to end up in a situation where I have to maintain (and extend) this mechanism if `extract_array()` is allowed to spit out random array-like stuff.

> One could imagine creating a seed that pushes computations such as %*% and rowSums to the cloud (or to Spark or whatever); such efficiencies would be lost if we were always forced to realize content in memory, either as a dense or sparse matrix.

Yes, as discussed earlier (also in issue #40), it would be great to support this but I don't think we need to relax `extract_array()`'s contract for that. All we need is a mechanism that allows us to know 2 things:

- is a given operation supported by the backend?

- based on the delayed operations carried by the object (in particular the operations that alter its geometry like subsetting or transposition) is it ok to push the computation to the backend (modulo maybe some adjustments like transposition)?

The way I see it this would completely bypass the block processing mechanism so `extract_array()` would not be involved. IMO this is a different problem.

**Comment by hpages** [comment]
One last thing. All we're talking about is replace code like
```
    for (bid in seq_len(nblock)) {
        viewport <- grid[[bid]]
        block <- read_block(x, viewport)
        ... do something with this block
    }
```
with
```
    readblock <- if (is_sparse(x)) read_sparse_block else read_block
    for (bid in seq_len(nblock)) {
        viewport <- grid[[bid]]
        block <- readblock(x, viewport)
        ... do something with this block
    }
```
so the pain is minimal compared to the gain (overall stability of the entire DelayedArray framework). Do you want the pain of the vaccine or the pain of the disease? I take the vaccine.

**Comment by LTLA** [comment]
> But you don't decide what operations others put on their DelayedArray objects and we still want `rowSums()` to perform optimally for them right?

I'm fine with loss of efficiency when someone applies a sparsity-breaking operation. It happens with **Matrix** Ops and I don't expect it to _not_ happen with **DelayedArray** Ops. In fact, it is unlikely that my code will be in a position to use your optimizations anyway, because I already use a sparsity-preserving algorithm in such cases to avoid loss of efficiency for `dgCMatrix` inputs.

> The delayed operation mechanism is a complex mechanism and is only maintainable because `extract_array()` has a very simple and well defined contract.

Seems like the entire **DelayedArray** framework should just support the abstract concept of an array rather than the specific ordinary/`dgCMatrix` implementations. 

> All we need is a mechanism that allows us to know 2 things:

I'll believe it when I see it. The loosened contract already solves this problem.

> Do you want the pain of the vaccine or the pain of the disease? I take the vaccine.

Seems worse than the disease in this case.

I have real use-cases in the form of three DA matrix classes in **BiocSingular** that are not sparse and only nominally dense. By implementing a matrix contract for their seeds, I could use the proposed approach in the PR to operate on the original representation throughout the DA framework. Unless you're going to give me an `extract_other_array()` mechanism?

**Comment by hpages** [comment]
> I'm fine with loss of efficiency when someone applies a sparsity-breaking operation

Things like `log(x + 1)` or `x / (x^2 + 10)` are not sparsity-breaking operations.

> I'll believe it when I see it. The loosened contract already solves this problem.

So we went from "One could imagine creating a seed that pushes computations such as %*% and rowSums to the cloud" to "problem solved". Impressive!

> Seems worse than the disease in this case.

The disease is very painful and has no cure. We're going to start seeing random failures for  operations like `rowSums(D)` because blocks are random data structures. What you really need to understand is that even disciplined and well intentioned backend developers will participate to this mess because they have no way to control how block data propagates from the seed to the top. This propagation is controlled by the various `extract_array()` methods for DelayedOp objects and the developer only controls the first `extract_array()` method i.e. the method for their seed objects.

> I have real use-cases in the form of...

What you've showed me so far does not justify loosening the `extract_array()`. But if you show me a convincing use case I could start considering it.

**Comment by LTLA** [comment]
> Things like `log(x + 1)` or `x / (x^2 + 10)` are not sparsity-breaking operations.

As far as I'm concerned, your `+` operation makes it sparsity breaking. I don't need **DelayedArray** to try to globally optimize my expressions, I can do that myself.

> So we went from "One could imagine creating a seed that pushes computations such as %*% and rowSums to the cloud" to "problem solved". Impressive!

Yes, it would be, if you didn't bind me to this dense/sparse requirement and let me use my own methods inside of **DelayedArray**'s block processing.

> We're going to start seeing random failures for operations like `rowSums(D)` because blocks are random data structures

Blocks are abstract matrices. If something is a matrix, it should support `rowSums`. 

If you want to be safe, just have `blockApply` (or whatever function) run `hasMethod` on the seed for your generic of interest and coerce to an array if it's `FALSE`. This solution would not require the backend developer to state support explicitly when it is implicit from the existence of a method.

> But if you show me a convincing use case I could start considering it.

Well, consider a matrix representation that switches between emitting dense and sparse blocks depending on the relative density of non-zero elements. This would be obviously faster for very sparse regions of the matrix while avoiding the overhead of tracking the extra indices for dense regions of the matrix.

**Comment by hpages** [comment]
> I don't need DelayedArray to try to globally optimize my expressions, I can do that myself.

Good for you but that's an important part of DelayedArray and I'm committed to keep it that way.

> Yes, it would be, if you didn't bind me to this dense/sparse requirement and let me use my own methods inside of DelayedArray's block processing.

I'll believe it when I see it.

> If something is a matrix, it should support rowSums.

We both know that this is not a reasonable expectation (e.g. matrix summarization on dgeMatrix objects).

> consider a matrix representation that switches between emitting dense and sparse blocks depending on the relative density of non-zero elements

This could be accommodated with an extra argument (e.g. `is.sparse`) to `read_block()` to switch between dense and sparse, with `is.sparse=NA` (the default) meaning "do your best". `read_block()` would still switch between using `extract_array()` and `extract_sparse_array()` internally so I still don't see the need to loosen `extract_array`'s contract for that.

**Comment by LTLA** [comment]
> I'll believe it when I see it.

There's hardly any incentive for me to write these methods when they're not going to get used.

> We both know that this is not a reasonable expectation (e.g. matrix summarization on dgeMatrix objects).

Hence the `hasMethod` checks. You'll need to check for support anyway, and if you check via `selectMethod` with `optional=TRUE`, you only pay the cost of S4 dispatch once.

I can see we've reached an impasse. Well, whatever. You can make the sausage in whatever way you like, just give me an API for the sparse case that's connected up to `%*%` and friends.

**Comment by hpages** [comment]
> just give me an API for the sparse case that's connected up to %*% and friends.

Use `is_sparse()` + `read_sparse_block()`.

Back to square one.

**Pull request closed without merging**
