### PR TITLE
Support extract_sparse_array for DelayedAbind objects.

### LINKED ISSUE #80: extract_sparse_array on DelayedAbind with sparse backends is not yet implement
For example:

```r
library(Matrix)
x <- rsparsematrix(10, 20, 0.1)
y <- rsparsematrix(10, 30, 0.1)

library(DelayedArray)
x0 <- DelayedArray(x)
y0 <- DelayedArray(y)

Z <- cbind(x0, y0)
is_sparse(Z) ## TRUE

colSums(Z) # or really, any operation on this.
## Error in extract_sparse_array(x@seed, index) : NOT IMPLEMENTED YET!
```

An immediate hack would be to treat all `DelayedAbind` as being non-sparse so that the above code works. Though maybe it might be better to just implement it, something like:

```r
.extract_sparse_array_from_DelayedAbind <- function(x, index)
{
    i <- index[[x@along]]

    if (is.null(i)) {
        ## This is the easy situation.
        tmp <- lapply(x@seeds, extract_sparse_array, index)

        last <- 0L
        for (a in seq_along(tmp)) {
            tmp[[a]]@nzindex[,x@along] <- tmp[[a]]@nzindex[,x@along] + last
            last <- last + dim(tmp[[a]])[x@along]
        }

        all.nzindex <- do.call(rbind, lapply(tmp, nzindex))
        all.nzdata <- unlist(lapply(tmp, nzdata))
        all.dims <- dim(tmp[[1]])
        all.dims[x@along] <- last

        # TODO: deal with the dimnames.
        return(SparseArraySeed(all.dims, nzindex=all.nzindex, nzdata=all.nzdata))
    }

    ## From now on 'i' is a vector of positive integers.
    dims <- get_dims_to_bind(x@seeds, x@along)
    breakpoints <- cumsum(dims[x@along, ])
    part_idx <- get_part_index(i, breakpoints)
    split_part_idx <- split_part_index(part_idx, length(breakpoints))
    FUN <- function(s) {
        index[[x@along]] <- split_part_idx[[s]]
        extract_sparse_array(x@seeds[[s]], index)
    }
    tmp <- lapply(seq_along(x@seeds), FUN)

    ## NOTE: this part is missing something to do with get_rev_index.
    last <- 0L
    for (a in seq_along(tmp)) {
        tmp[[a]]@nzindex[,x@along] <- tmp[[a]]@nzindex[,x@along] + last
        last <- last + dim(tmp[[a]])[x@along]
    }

    all.nzindex <- do.call(rbind, lapply(tmp, nzindex))
    all.nzdata <- unlist(lapply(tmp, nzdata))
    all.dims <- dim(tmp[[1]])
    all.dims[x@along] <- last

    # TODO: deal with the dimnames.
    return(SparseArraySeed(all.dims, nzindex=all.nzindex, nzdata=all.nzdata))
}

setMethod("extract_sparse_array", "DelayedAbind", .extract_sparse_array_from_DelayedAbind)
```

### PR DESCRIPTION
**Pull request by LTLA**
Pretty much as it says:

```r
library(Matrix)
x <- rsparsematrix(10, 20, 0.1)
colnames(x) <- letters[1:20]
y <- rsparsematrix(10, 30, 0.1)
colnames(y) <- 1:30

library(DelayedArray)
x0 <- DelayedArray(x)
y0 <- DelayedArray(y)

Z <- cbind(x0, y0)
is_sparse(Z) 
## [1] TRUE

all.equal(colSums(Z), colSums(as.matrix(Z)))
## [1] TRUE

all.equal(colSums(Z[,50:1]), colSums(as.matrix(Z)[,50:1]))
## [1] TRUE
```

Wasn't entirely sure where to put these tests, given that there don't seem to be any RUnit function for `DelayedAbind`.

Closes #80.

### CODE REVIEW

**Comment by hpages** [comment]
Looking into this now. Sorry for the delay.

**Comment by hpages** [comment]
So the real important piece that was missing here is an `abind()` for SparseArraySeed objects. I'm adding one to `SparseArraySeed-utils.R`. Does what your `.combine_abinded_sparse_array_seeds()` does but follows the style of `simple_abind()` and uses `get_dims_to_bind()`, `combine_dims_along()`, and `combine_dimnames_along()`. Will have unit tests.

**Comment by LTLA** [comment]
okay great. Should I close this?

**Comment by hpages** [comment]
I'll close when things are ready/pushed.

**Comment by hpages** [comment]
Merged with some minor edits via commit d03a6beafabb39d9a6bee33ba2004c931fecaf61 (DelayedArray 0.17.5). Thanks!

**Pull request closed without merging**
